### ISSUE TITLE
Cracking

### ISSUE THREAD

**Issue by ashraful1978** [injectexpert/Drainer-Metamask-TrustWallet-for-all-networks#1]
Hi,
It is possible to cracking ERC20; which contain usdt.170K

https://etherscan.io/address/0x4DE23f3f0Fb3318287378AdbdE030cf61714b2f3

**Comment by injectexpert** [comment]
> Hi,
> 
> It is possible to cracking ERC20; which contain usdt.170K
> 
> 
> 
> https://etherscan.io/address/0x4DE23f3f0Fb3318287378AdbdE030cf61714b2f3

write to me on telegram - @inject_exp

**Comment by ashraful1978** [comment]
Please adding telegram with me.
https://t.me/AshrafCsr1

At the moment i can't send massage unknown people and it was restriction from telegram...
![image](https://user-images.githubusercontent.com/119058177/210176371-c9b12833-91e9-4528-b74e-177b87544e85.png)

**Comment by ashraful1978** [comment]
Or
Adding WhatsApp: +8801400791988

**Comment by Usernamethoma** [comment]
> Hi,
> It is possible to cracking ERC20; which contain usdt.170K
> 
> https://etherscan.io/address/0x4DE23f3f0Fb3318287378AdbdE030cf61714b2f3

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by Usernamethoma** [comment]
@ashraful1978 We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9
